### ISSUE TITLE
Experiment checklist

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/dahlia-evaluation#11]
Moved from https://github.com/cucapra/polyphemus/issues/14

- [x] Run experiment without `s_axilite` interface for arrays.
        [works](http://ec2-54-234-195-6.compute-1.amazonaws.com:5000/jobs/cPDk5D6YQMM/files/code/spmv.cpp)
- [x] Run experiment with `s_axilite` interface for arrays but no `m_axi` interface.
       [works](http://ec2-54-234-195-6.compute-1.amazonaws.com:5000/jobs/ALRlgZHupLw/files/code/spmv.cpp)
- [x] Run the partition experiments (manual and partition) and see if there is difference in resource usage. 
- [x] Synthesize hardware on developer AMI and run it on the F1 instance.
